### PR TITLE
"demandforecast2.ipynb" notebook 

### PR DESCRIPTION
**Pull request by subhashreerautray-tudip**
- Updated the code to use "pandas_gbq".
- Removed 'authenticate_user' code.

### CODE REVIEW

**Comment by subhashreerautray-tudip** [comment]
Hi @yankovai-google 

I tried and proceed with BigQuery magic functions, but while running the 4th cell of the notebook, getting "AttributeError: 'DataFrame' object has no attribute 'execute'".  Can you please look into it?

Please find the screenshot for the same: https://screenshot.googleplex.com/HPPTYL2Gs8C

-Thanks

**Comment by yankovai-google** [comment]
The whole notebook needs to be reworked to use the bigquery magic function.
You no longer need the pandas-gbq and pandas_gbq libraries. You also don't
need the query_to_dataframe function anymore. For example, cell 8 would get
replaced with the following lines:

%%bigquery
SELECT * FROM `bigquery-public-data.new_york.tlc_yellow_trips_2015` LIMIT 10

**Comment by subhashreerautray-tudip** [comment]
Hi @yankovai-google 

Sorry for the confusion here.

Actually the notebook related to the lab(https://googlestaging.qwiklabs.com/labs/1656/edit) is "https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/CPB100/lab4a/demandforecast.ipynb" and while running the notebook, getting some errors, but proceeded further by updating the cell with BigQuery magic functions. Please find the updated cell.

Updated code for 2nd cell:

!bq show --schema --format=prettyjson  bigquery-public-data:new_york.tlc_yellow_trips_2015

Updated code for 3rd cell:

%%bigquery 
SELECT 
  EXTRACT (DAYOFYEAR from pickup_datetime) AS daynumber
FROM `bigquery-public-data.new_york.tlc_yellow_trips_2015` 
LIMIT 5

Updated code for 4th cell:

%%bigquery taxiquery
WITH trips AS (
  SELECT EXTRACT (DAYOFYEAR from pickup_datetime) AS daynumber 
  FROM `bigquery-public-data.new_york.tlc_yellow_trips_*`
  WHERE _TABLE_SUFFIX BETWEEN '2014' AND '2016'
)
SELECT daynumber, COUNT(1) AS numtrips FROM trips
GROUP BY daynumber ORDER BY daynumber

But while running the 5th cell, I am getting an error "AttributeError: 'DataFrame' object has no attribute 'execute'", screenshot: https://screenshot.googleplex.com/HPPTYL2Gs8C

I am not getting any solution of above issue and found the similar notebook demandforecast2.ipynb (https://github.com/GoogleCloudPlatform/training-data-analyst/blob/master/CPB100/lab4a/demandforecast2.ipynb) which I thought can be used in this lab.

Can you please help me to resolve above issue?

-Thanks

**Comment by yankovai-google** [comment]
I would remove the taxiquery function and the subsequent cell that calls
it. Replace the function with:

%%bigquery trips --params {"YEAR": "2015"}
WITH trips AS (
  SELECT EXTRACT (DAYOFYEAR from pickup_datetime) AS daynumber
  FROM `bigquery-public-data.new_york.tlc_yellow_trips_*`
  where _TABLE_SUFFIX = @YEAR
)
SELECT daynumber, COUNT(1) AS numtrips FROM trips
GROUP BY daynumber ORDER BY daynumber

**Comment by subhashreerautray-tudip** [comment]
Hi @yankovai-google 

Thanks for the valuable suggestions.

I have updated the notebook accordingly.
Please find the updated notebook: https://github.com/subhashreerautray-tudip/training-data-analyst/blob/455834e6272a0842dfc694638c8417fa60b7a839/CPB100/lab4a/demandforecast.ipynb

But I am still facing issues with updating "Adding 2014 and 2016 data" section as it is using "for" loop to add data.

Can you please assist me to update the below cell:

data2 = data # 2015 data
for year in [2014, 2016]:
    query_parameters = [
      {
        'name': 'YEAR',
        'parameterType': {'type': 'STRING'},
        'parameterValue': {'value': year}
      }
    ]
    weather = wxquery.execute(query_params=query_parameters).result().to_dataframe()
    trips = taxiquery.execute(query_params=query_parameters).result().to_dataframe()
    data_for_year = pd.merge(weather, trips, on='daynumber')
    data2 = pd.concat([data2, data_for_year])
data2.describe()

**Comment by subhashreerautray-tudip** [comment]
Hi @yankovai-google 

Any update here?

**Comment by yankovai-google** [comment]
Hi @subhashreerautray-tudip --

My apologies, I did not read the lab carefully before suggesting we use the
bigquery magic function. Since we have the loop we should go back to using
pandas-gbq. Would you be able to revert back? If not let me know and I can
make the corrections.

**Comment by subhashreerautray-tudip** [comment]
Hi @yankovai-google 
This PR #771 is updated according to 'pandas-gbq'. As per this thread discussion, I made the changes only in "demand forecast. ipynb". 

Since both the notebooks are similar (demandforecast is using magic function and demandforecast2 uses pandas-gbq), we can stop using "demandforecast. ipynb" notebook and instead of that we can use the updated one.

Can you please go ahead and merge the PR?

Once it is merged, we will update all the labs having 'demandforecast.ipynb' with 2nd notebook.

Thanks

**Comment by subhashreerautray-tudip** [comment]
Hi @yankovai-google 

This PR is already updated according to 'pandas-gbq'. Can you please go ahead and merge the PR as related lab is merged into master (PR: https://github.com/CloudVLab/gcp-training-content/pull/2615).

**Comment by subhashreerautray-tudip** [comment]
Hi @yankovai-google 

Any update here?

**Pull request merged**
