### PR TITLE
Notebook Updates - keras_dnn_babyweight.ipynb

### PR DESCRIPTION
**Pull request by mahakverma-tudip**
- Updated latest version of BigQuery in keras_dnn_babyweight.ipynb in both labs and solutions folder
- Reference buganizer: http://b/264640329

### CODE REVIEW

**Comment by mahakverma-tudip** [comment]
Hi @gwendolynstripling 
Please review the changes and merge the PR. Thanks!

**Comment by mahakverma-tudip** [comment]
Hi @gstripling Please review the changes and merge the PR. Thanks!

**Comment by gstripling** [comment]
Hi - I get an "invalid Notebook" error when I click on the Notebook to review the changes.

**Comment by gstripling** [comment]
Hello - I receive the following message when attempting to review the Notebook:  Invalid notebook file. Please make sure both before and after version of the file contains valid notebook JSON.

If the problem persists, please write to us at support@reviewnb.com

**Comment by mahakverma-tudip** [comment]
Hi @gwendolynstripling , we are able to access the notebook successfully with the updated changes. 
Please review the changes and merge the PR. Thanks!

**Comment by mahakverma-tudip** [comment]
Hi @damonarunion , 
Please review the changes and merge the PR. Thanks!

**Review by damonarunion — APPROVED** [review]
lgtm

**Pull request merged**
