### PR TITLE
Remove unnecessary mkdir

### PR DESCRIPTION
**Pull request by marksteve**

### CODE REVIEW

**Comment by marksteve** [comment]
I signed it!

**Comment by lakshmanok** [comment]
The sample directory is not necessarily present the first time you run the lab.
Perhaps change this to "mkdir -p"
That will avoid the error message if the directory already exists.

**Comment by marksteve** [comment]
@lakshmanok It is: https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/courses/machine_learning/feateng/sample

**Comment by marksteve** [comment]
But yeah, maybe it's better to clear that dir and change it to a `mkdir -p`

**Pull request closed without merging**
