### PR TITLE
Updated default CMLE tier to GPU

### PR DESCRIPTION
**Pull request by PraneetDutta**
Changed training tier as per discussion for the ReadMe and Ipython notebook.

### CODE REVIEW

**Comment by lakshmanok** [comment]
Praneet, could you please fix the conflict?

**Comment by mylenebiddle** [comment]
@PraneetDutta please resolve the conflict for the merge.

**Comment by PraneetDutta** [comment]
I missed this, updating it now.

**Comment by PraneetDutta** [comment]
Updated

**Comment by mylenebiddle** [comment]
Thanks @PraneetDutta, merged.

**Pull request merged**
