### PR TITLE
python 3 compatibility and ensuring np.arccos be between -1 and 1

### PR DESCRIPTION
**Pull request by dedeco**
Sorry, but "create issue" is disabled for this repo, so I just did the pull request. The modifications are very simple.

I participated of Bootcamp Google summit - SP and during the session qwickslabs I found this simple issues.

### CODE REVIEW

**Comment by dedeco** [comment]
Yes. I signed it!

**Comment by lakshmanok** [comment]
Thanks for the pull request. Unfortunately, we're not ready to update the metadata fields to 3.0.
I'll take the np.arccos fix and print() fixes, though if you could remove the metadata changes.

**Comment by dedeco** [comment]
Sure! I will remove! 

I found similar issues in other notebooks, Do you mind if i fix them? I did this first just to check if the community will be recepty for small issues.

I intend to run all notebooks to help me in my research, and if be possible be more helpful I'll be happy in help in contribute more deeper.

If it's ok, let me know If i can commit the notebooks results, because it can be some small diferences, eg: Test RMSE: 6.15 can change to 6.17, something like that. Or I can just save the code only differences and test separately.

**Comment by lakshmanok** [comment]
Small differences in the results is okay.  But make sure to "clear" cells whose output is not checked in.

**Pull request merged**
