### PR TITLE
Applying rollback to images lab

### PR DESCRIPTION
**Pull request by danideter**
Also added grammatical fixes from #705

### CODE REVIEW

**Comment by danideter** [comment]
Ah, wait, sorry Chris, merge conflicts in the docs. Let me fix them real fast.

**Comment by ryangillard** [comment]
As discussed between the three of us (you, Chris, and I) there is no need for a rollback here. These are currently all perfectly working labs. As suggested by Chris and I, if you want to add test.py to the trainer folder then you should create a new PR for just that and close this PR. However, it was already discussed and decided by many of us that those almost 100 lines of unit tests in test.py don't really flow with the main story of the lab or add much value and are more of a distraction and confusion point for students. Perhaps, these could be more useful for a different audience. Furthermore, in the commits of this PR there are many changes that were already changed correctly by Chris in his reviewed and merged PR so there is a lot of redoing of work. Additionally, some errors have now been introduced such as adding periods to the end of comments that aren't sentences, etc.

**Comment by crawles** [comment]
I'm agreeing with Ryan here, Danielle. Especially since the labs are working well right now. It's introducing unneeded complexity. I think the most direct route to getting your tests in would actually be to add them in directly. It will reduce unnecessary review since I have already added these changes.

I am okay with having the tests in the lab. Of course the students don't have to dive into the details if they don't want to, but they will know the tests are passing.

**Comment by danideter** [comment]
Hey guys, so I noticed there were other changes to the code while I was doing the rollback such as the code being passed to docker is no longer a python package. This will be more work for us in the future when we ween off of docker, and probably what caused the tests to fail in the first place.

Could you please link that discussion, Ryan? When I first had this lab reviewed #608 , the reviewers said the tests were a good addition. I originally had the tests outside the notebook so that it wouldn't take up too much space for the reasons you describe, but you also told me that you prefer the trainer folder get dynamically created. Would you have a preference between having the tests in the lab vs outside of it?

If you both feel that strongly about not doing a rollback, could one of you to please send me a pull request that 1) reintroduces the tests and 2) returns the code to a python module? This code was broken live during a cohort, and my goal here is to prevent that from happening again.

**Comment by danideter** [comment]
Closing as obsolete thanks to https://github.com/GoogleCloudPlatform/training-data-analyst/pull/802

**Pull request closed without merging**
