### PR TITLE
Fix missing cloud function runtime

### PR DESCRIPTION
**Pull request by Shikanime**
# Securing and Integrating Components of your Application

## Qwiklabs – Deploying an API for the Quiz Application

**Describe the bug**

The prepare file does not work because of the missing runtime argument.

**To Reproduce**

1. Go to `training-data-analyst/courses/developingapps/nodejs/cloudendpoints/start`
2. Run `. prepare_environment.sh`
3. See error

```shell
# ...
ERROR: (gcloud.beta.functions.deploy) Missing required argument [runtime]: Flag `--runtime` is required for new functions.
Project ID: qwiklabs-gcp-7ef225354a0fd6b5
# ...
```

**Expected behavior**

We need to add execution environment for a first initialization of the cloud function.

```bash
# ...
gcloud beta functions deploy process-feedback --trigger-topic feedback --source ./function --stage-bucket $GCLOUD_BUCKET --entry-point subscribe
# ...
```

### CODE REVIEW

**Comment by Shikanime** [comment]
I signed it!

**Comment by flashadvocate** [comment]
@Shikanime thanks for submitting! Ran into this today and was about to open a PR of my own, but someone got to it first! :)

**Comment by dmorellet** [comment]
Why not nodejs8 ?

**Comment by Shikanime** [comment]
@dmorellet No particular reason, perhaps at that time nodejs 8 was still in beta.

**Comment by dmorellet** [comment]
Hi @Shikanime, can you solve the conflict and ask to merge this PR please ? I would be so helpful for the poor students that will encounter these errors :)

**Comment by mylenebiddle** [comment]
Thanks - merging.

**Pull request merged**
