### PR TITLE
Restore of previous commit and partial python 3 changes

### PR DESCRIPTION
**Pull request by netskink**
@alexhanna we share a common goal with @lakshmanok to get python 3 versions of these notebooks.  I noticed one of your fixes to do this was overwritten.  I restored the bash code for account perms which uses python3.

The overall notebook is python 2 and not python 3 sadly.  The local predict part for this notebook fails in python 3.  The notebook runs start to finish now but its python 2 due to this limiting factor.

I also added some comments regarding some of the steps and adjusted the training steps for the cloud job to be 1000 so to be consistent with the other training steps used earlier.

### CODE REVIEW

**Comment by alexhanna** [comment]
@netskink can you let me know what parts of this you're working on? The local predict failure is a known bug. We're been chatting with the folks who work on the Cloud SDK about this.

I'm currently focusing on everything in the courses/deepdive/ folder.

**Comment by netskink** [comment]
@alexhanna I was going to do the taxifeat as part of the feature engineering exercise next.  It still has the uneeded python package bit in there.  I also plan to look at it some more regarding the add_engineered() bit of code.  I had a problem earlier with my one-off version of this notebook where the  model broke when I added additional features.  I am not certain if its because the test input needed changes or if was something I broke in my one-off version.  Nice to meet you Alex.

**Comment by netskink** [comment]
I added the variables for modle name, training directory, revision, etc so that they can be parameterized and kept separate easily.  My goal was to make them consistent across all labs one notebook at a time.  Feateng would be the second and cloudmle was the first.

The additional comments help understand the notebooks.  I was trying to clarify and fix up the code so that the next person would have an easier time than I did.

The bigger problem to me is why doesn’t the cloud ml engine predict with the same input as the local version given the underlying task and model code is the same.

**Comment by netskink** [comment]
With the variables for the module name and versions I was going to experiment with tweaking the name so that it was unique and possible to run the two models side by side to isolate the problem.  As it is now I delete the contents of my bucket so that only one taxifare model exists at one time.

**Comment by alexhanna** [comment]
@netskink,

I think the changes make sense, and I do appreciate them. To make that change, though, we'll have to make the edits in other places in our repository. We'll have to think through how those changes affect learners, however. I suggest taking some of the suggestions and creating an issue we can consider for the next version of code in this repo.

Could you explain the other issue? What output are you getting from the local prediction that differs from the Cloud ML one?

**Comment by netskink** [comment]
This commit aligns feateng with the previous lab e_cloudmle.  It does this by 

* moves the entire project from an upper level directory with a symbolic link to the lower 04_feature_eng dir similar to how 03_tensorflow and e_cloudmle notebooks.
* the notebook name and training dirs have a common root of taxifare with a suffix of feateng to distinguish from the regular taxifare used by e_cloudmle.
* Since the model name, training dir, version number are parameterized they can really be anything you want but at form is consistent.
* The unneeded egg package info files with the census code in them has been removed to avoid confusion.
* The ordering of tensorboard starting before the training dir removal has been used as in the cloud mle.  The file mentioned the rmse but was never demonstrated how to obtain.  I presume it was in tensorboard.  At least now tensorboard is in place.
* The error where the model trained locally versus trained using the cloud microservice still persists.  Likewise the beam error.  However now its a simple matter of running the code to see the error since its all in the notebook whereas it was not before.

**Comment by netskink** [comment]
@alexhanna I can add an issue.  I'm trying to think how it would be best to show the error.  I did a large commit today.  Tomorrow I can add code which shows how it runs and does not.  For now the code only shows the error.  It does not show the fix.  I ran this code in my own version and the fix was to supply the engineered features as new columns in prediction which I do not think is a true fix but at least it ran.

Since I don't know how to evaluate what is going on during cloud training, I don't know if it is really working.  I guess I could deploy stackdriver or something to log it.

Lastly, regarding how it impacts other learners.  I was a student in the class.  One problem I had with the hop between the class was how changes were inconsistent in some of the notebooks.  For instance, one notebook might change multiple methods simultaneously introducing multiple new topics.  The feateng notebook is a good example.  It adds beam, feature crosses, engineered features, and an custom evaluate function in the same notebook.  It also mentions hyperparameter tuning.  The location of the notebook is an inconsistent location and the format of the notebook varies from the previous lesson where cloudmle was first introduced.  Both notebooks have unnecessary files in them eg the egg info files.  Hence, why I am trying to clean them up and help out the next student.

**Comment by netskink** [comment]
When I am running tensorboard, I am getting this warning message.

```
/usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/utils/__init__.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .murmurhash import murmurhash3_32
/usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/utils/extmath.py:24: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._logistic_sigmoid import _log_logistic_sigmoid
/usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/metrics/cluster/supervised.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .expected_mutual_info_fast import expected_mutual_information
/usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/metrics/pairwise.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan

```

Is this ok?

**Comment by alexhanna** [comment]
> When I am running tensorboard, I am getting this warning message.
> 
> ```
> /usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/utils/__init__.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   from .murmurhash import murmurhash3_32
> /usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/utils/extmath.py:24: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   from ._logistic_sigmoid import _log_logistic_sigmoid
> /usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/metrics/cluster/supervised.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   from .expected_mutual_info_fast import expected_mutual_information
> /usr/local/envs/py2env/lib/python2.7/site-packages/sklearn/metrics/pairwise.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
>   from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
> ```
> Is this ok?

This is fine.

**Comment by alexhanna** [comment]
> @alexhanna I can add an issue. I'm trying to think how it would be best to show the error. I did a large commit today. Tomorrow I can add code which shows how it runs and does not. For now the code only shows the error. It does not show the fix. I ran this code in my own version and the fix was to supply the engineered features as new columns in prediction which I do not think is a true fix but at least it ran.
> 
> Since I don't know how to evaluate what is going on during cloud training, I don't know if it is really working. I guess I could deploy stackdriver or something to log it.
> 
> Lastly, regarding how it impacts other learners. I was a student in the class. One problem I had with the hop between the class was how changes were inconsistent in some of the notebooks. For instance, one notebook might change multiple methods simultaneously introducing multiple new topics. The feateng notebook is a good example. It adds beam, feature crosses, engineered features, and an custom evaluate function in the same notebook. It also mentions hyperparameter tuning. The location of the notebook is an inconsistent location and the format of the notebook varies from the previous lesson where cloudmle was first introduced. Both notebooks have unnecessary files in them eg the egg info files. Hence, why I am trying to clean them up and help out the next student.

I do appreciate the clean up, and that's helpful feedback. But for now, we want to focus on Python 2 to 3 conversion. As a team, we're going to have to look at this codebase and look for good places to refactor and to abstract away some places for learners. Please revert the changes.

**Comment by netskink** [comment]
"Please remove your credentials"  Are you talking about the bucket and project settings?

**Comment by alexhanna** [comment]
> "Please remove your credentials" Are you talking about the bucket and project settings?

Yes.

**Comment by netskink** [comment]
Indeed.  That is a problem.  To be honest, I am just about to upload another patch.  This page [here](https://cloud.google.com/ml-engine/docs/tensorflow/packaging-trainer#project-structure) shows a difference in the location of setup.py from the code.  Possibly the api changed.  In the document, setup.py is peer to the overall project directory.  In the repo its in the trainer subdir.  I'm getting this feeling the cloud submit job is working but not with the proper inputs.

There is also the name='trainer' assignment in the setup.py file.  In the sample it is specified as trainer but in the repo the name is different.  Which is correct?

Lastly, are you able to predict with /tmp/test.json file used to test the locally trained model?

**Comment by netskink** [comment]
This could be the problem with the cloud prediction and the different number of inputs.  Notice the data path parameters for the local model.  It is using the beam results.

```
%%bash
rm -rf taxifare.tar.gz taxi_trained
export PYTHONPATH=${PYTHONPATH}:${PWD}/taxifare
python -m trainer.task \
  --train_data_paths=${PWD}/sample/train.csv \
  --eval_data_paths=${PWD}/sample/valid.csv  \
  --output_dir=${PWD}/taxi_trained \
  --train_steps=1000 \
  --job-dir=/tmp
```

Now look at the code which does have a tensorboard examination and its datapath settings.  This is last model training cell.

```
%%bash

WARNING -- this uses significant resources and is optional. Remove this line to run the block.

OUTDIR=gs://${BUCKET}/taxifare/feateng2m
JOBNAME=lab4a_$(date -u +%y%m%d_%H%M%S)
TIER=STANDARD_1 
echo $OUTDIR $REGION $JOBNAME
gsutil -m rm -rf $OUTDIR
gcloud ml-engine jobs submit training $JOBNAME \
   --region=$REGION \
   --module-name=trainer.task \
   --package-path=${PWD}/taxifare/trainer \
   --job-dir=$OUTDIR \
   --staging-bucket=gs://$BUCKET \
   --scale-tier=$TIER \
   --runtime-version=$TFVERSION \
   -- \
   --train_data_paths="gs://cloud-training-demos/taxifare/train*" \
   --eval_data_paths="gs://cloud-training-demos/taxifare/valid*"  \
   --output_dir=$OUTDIR \
   --train_steps=418168 \
   --train_batch_size=512 --nbuckets=16 --hidden_units="64 64 64 8"
```

I don't have access to that bucket to examine the csv files to see how many columns are present.  But if you notice the bucket used by the cloud trained model I have problems with has yet another method to access the input data.  At least this time, I do know it is copies of the beam output similar to the local model.  Which is puzzling to me.


```
%%bash
OUTDIR=gs://${BUCKET}/taxifare/ch4/taxi_trained
JOBNAME=lab4a_$(date -u +%y%m%d_%H%M%S)
echo $OUTDIR $REGION $JOBNAME
gsutil -m rm -rf $OUTDIR
gcloud ml-engine jobs submit training $JOBNAME \
  --region=$REGION \
  --module-name=trainer.task \
  --package-path=${PWD}/taxifare/trainer \
  --job-dir=$OUTDIR \
  --staging-bucket=gs://$BUCKET \
  --scale-tier=BASIC \
  --runtime-version=$TFVERSION \
  -- \
  --train_data_paths="gs://$BUCKET/taxifare/ch4/taxi_preproc/train*" \
  --eval_data_paths="gs://${BUCKET}/taxifare/ch4/taxi_preproc/valid*"  \
  --train_steps=5000 \
  --output_dir=$OUTDIR
```

**Comment by netskink** [comment]
This latest commit has

* the credentials removed
* tensorboard is added to each step.  All the results look good except for the cloud training job.  However both are similar.  Its like the inputs are invalid or not being used.  Looking at the paths given to the job I don't see the problem though.  The cloud predict for cloud mle works where the one for feateng does not.

Here are the three cloudmle results
cloud-mle-003
cloudmle-002
cloud-mle-01


Here are the three feateng results
feateng-003
feateng-002
feateng-001

**Comment by lakshmanok** [comment]
Thanks for reporting the error with mlengine predict.  The problem turned out to be that the code was adding engineered features to the same dictionary that was used for the placeholders. This didn't trip any error in earlier versions of TensorFlow (since the added features were not placeholders), but the new version checks the input and throws an error.  I have now fixed this in this commit:  https://github.com/GoogleCloudPlatform/training-data-analyst/commit/2841d96cab5d7df36d870bb21dd94d29770aace0 

In combination with Alex's commits for Python 3, all the outstanding problems are fixed, so I will close this issue.

it will be difficult to merge any of these changes into the modified branch, so could you start a new pull request if you want to suggest any changes?

**Comment by netskink** [comment]
Super. I’ll try it.  I appreciate it.

**Pull request closed without merging**
