### PR TITLE
update notebooks from tf contrib to core

### PR DESCRIPTION
**Pull request by amygdala**

### CODE REVIEW

**Comment by amygdala** [comment]
Lak, what do you think of these  updates from contrib --> core? I believe that with these changes, RMSE now needs to look at `average_loss`.
I didn't yet make any changes related to datasets or `tf.estimator.train_and_evaluate()`. (So, I didn't yet change the Experiment notebook. I figure that incremental changes are better given my jetlag).
@lakshmanok

**Comment by amygdala** [comment]
Update: I just discovered that you've already updated the feateng version of this example to tf >= 1.4 , 
so it looks like it just remains to backport those changes to these notebooks and the cmle/taxifare/trainer module.  
You probably already have that in progress?-- if so, we can just close this PR.

**Comment by osipov** [comment]
Amy, Lak, we are running Data Engineering classes this week that rely on this content. Looking at the proposed changes in the PR, it looks like the slides that we are using for the class may get out of sync with the code in the notebooks. Let's make sure that these changes are in sync with the upcoming DE v1.2 class content.

@amygdala @lakshmanok

**Comment by lakshmanok** [comment]
Amy, these changes look good and do need to be made.  However, we are waiting to do this when we release Data Engineering v1.2 (Carl, don't worry ...).  The reason we didn't bother staging it in a separate branch is that we already have the TF 1.4 versions in

https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/courses/machine_learning/deepdive/03_tensorflow

so just a matter of copying over the relevant notebook & code.

Unfortunately, the old feateng notebook wouldn't run in TF1.5 in a class last week (something was not backwards compatible), so rather than troubleshoot on the fly, the instructor just updated it to tf.estimator even though the slides don't match.

**Comment by amygdala** [comment]
I'll close this as per our discussion.

**Pull request closed without merging**
