### PR TITLE
ahybrid: fix gcloud auth issue for kubectl

### PR DESCRIPTION
**Pull request by hudomju**
https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

### CODE REVIEW

**Comment by hudomju** [comment]
@damonarunion could you review and merge, please?

**Review by damonarunion — APPROVED** [review]

**Comment by damonarunion** [comment]
Use the "Reviewers" option in the future, find (damonarunion) and add me as a Reviewer.  

Merge complete.

**Comment by hudomju** [comment]
@damonarunion thanks - could you grant me permissions to assign the PR to you as a Reviewer? A the moment I cannot do it myself, that's why I wrote your name in the comments.

**Comment by damonarunion** [comment]
Got it.  No, I don't have admin privileges.    Just continue mentioning me if that is your only option.  I requires an extra step from me but it is not a big deal. @clupone-g (FYI).

**Pull request merged**
