### PR TITLE
Added deepdive2 structured solutions and labs

### PR DESCRIPTION
**Pull request by ryangillard**
Sorry, had to redo so that it would show up under my username and not DeepLearning VM for CLA checking.

### CODE REVIEW

**Comment by ryangillard** [comment]
Most of them are in the serving folder for the app engine app. The main
files are 24 notebooks, 46 images in the assets folders, and like 16 files
in the serving folders. The rest are as I said.

**Comment by lakshmanok** [comment]
Ryan, I'd created keras_dnn and keras_wd and bqml versions in the structured folder? Do these notebooks include stuff from those notebooks?  (e.g. I have pass-through keys in them)

**Comment by danideter** [comment]
I know I haven't done web development for a while now, but I'd be surprised if we really needed 980 files :)
Regardless, there's way too much stuff here to be reviewed at once. Could you please make a new branch and we'll review the labs one at a time? I can help you simplify the material. Plus, it's Google policy to keep code changes small. I understand this content refresh may be a bit of an exception, but almost a thousand files is too much.

**Comment by ryangillard** [comment]
> Ryan, I'd created keras_dnn and keras_wd and bqml versions in the structured folder? Do these notebooks include stuff from those notebooks? (e.g. I have pass-through keys in them)

I used some of those as a base. I got rid of the pass-through keys because including the hashcolumn in a big dataset I thought was a wasteful use of data flow and students in the past get confused by the whole thing, so keeping it to actual features that will be trained on is a win for both. The pass through key was more just to show that the outputs are in the same order as the inputs, but we cover that in more data efficient ways elsewhere.

**Comment by ryangillard** [comment]
> I know I haven't done web development for a while now, but I'd be surprised if we really needed 980 files :)
> Regardless, there's way too much stuff here to be reviewed at once. Could you please make a new branch and we'll review the labs one at a time? I can help you simplify the material. Plus, it's Google policy to keep code changes small. I understand this content refresh may be a bit of an exception, but almost a thousand files is too much.

940 or so of those files are from the serving application lib, etc. if you check the file list. I'll just close this pull request and make one for every lab.

**Comment by danideter** [comment]
Ryan, why did you commit the app engine code without it getting reviewed? These files are unnecessary. That's exactly what I was trying to avoid.

https://github.com/GoogleCloudPlatform/training-data-analyst/commit/cd93b1fb69b56a60dda4cf81f9f3af50a5a9b275

**Pull request closed without merging**
