### PR TITLE
Moving the new image labs into master

### PR DESCRIPTION
**Pull request by danideter**

### CODE REVIEW

**Comment by danideter** [comment]
Hi team, just moving the image labs into master. Did I follow the format correctly?

**Comment by BenoitDherin** [comment]
<p>LGTM</p>

**Comment by danideter** [comment]
Thanks Benoit!

**Comment by jonesevan** [comment]
Could we rename the labs with a numerical prefix so students know which one to open first?
1_mnist_linear
2_mnist_models

Going through the ipynbs now -- thanks for building these Danielle

**Pull request merged**
